const swaggerAutogen = require('swagger-autogen')()

const outputFile = './swagger_output.json'
const endpointsFiles = ['./Routes/routes.js']

const doc = {
    info: {
        version: "2.0.0",
        title: "Swaap",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    // host: "swaap-d45nq.ondigitalocean.app/api",
    // host: "backend.theswaap.com/api",
    host: "localhost:4050/api",
    // schemes: ['https', 'http'],
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    // tags: [{
    //     "name": "Mom's Food",
    //     "description": "API for MOM's Food portal"
    // }],
    basePath: '/',
    securityDefinitions: {
        bearerAuth:{
            type: 'apiKey',
            name: 'authorization',
            scheme: 'Bearer',
            in: 'header',
            "description":"Ex: Bearer 14213841804v323v3...."
        },
    },
    security: { bearerAuth: [] }
}

swaggerAutogen(outputFile, endpointsFiles,doc)